const bloggersData = [
  {
    id: 1,
    src: "/img/3.jpg",
    alt: "фото профиля",
    category: "История",
    network: {
      instagram: {
        icon: "/icons/instagram.png",
        link: "https://instagram.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты instagram",
        cpv: "cpv instagram",
        er: "er",
        services: [
          { name: "Рилс", price: 5000 },
          { name: "История", price: 3000 },
          { name: "Пост", price: 4000 },
        ],
      },
      youtube: {
        icon: "/icons/youtube.png",
        link: "https://youtube.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Интеграция", price: 15000 },
          { name: "Упоминание в видео", price: 7000 },
        ],
      },
      telegram: {
        icon: "/icons/telegram.png",
        link: "https://t.me/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Реклама в посте", price: 2000 },
          { name: "Закрепленный пост", price: 5000 },
        ],
      },
      vk: {
        icon: "/icons/vk.png",
        link: "https://vk.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 250,
        reach: "охваты vk",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Пост", price: 3500 },
          { name: "История", price: 2500 },
        ],
      },
    },
  },
  {
    id: 2,
    src: "/img/3.jpg",
    alt: "фото профиля",
    category: "Путешествия",
    network: {
      instagram: {
        icon: "/icons/instagram.png",
        link: "https://instagram.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты instagram",
        cpv: "cpv instagram",
        er: "er",
        services: [
          { name: "Рилс", price: 5000 },
          { name: "История", price: 3000 },
          { name: "Пост", price: 4000 },
        ],
      },
      youtube: {
        icon: "/icons/youtube.png",
        link: "https://youtube.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Интеграция", price: 15000 },
          { name: "Упоминание в видео", price: 7000 },
        ],
      },
      telegram: {
        icon: "/icons/telegram.png",
        link: "https://t.me/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Реклама в посте", price: 2000 },
          { name: "Закрепленный пост", price: 5000 },
        ],
      },
      vk: {
        icon: "/icons/vk.png",
        link: "https://vk.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 250,
        reach: "охваты vk",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Пост", price: 3500 },
          { name: "История", price: 2500 },
        ],
      },
    },
  },
  {
    id: 3,
    src: "/img/3.jpg",
    alt: "фото профиля",
    category: "Путешествия",
    network: {
      instagram: {
        icon: "/icons/instagram.png",
        link: "https://instagram.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты instagram",
        cpv: "cpv instagram",
        er: "er",
        services: [
          { name: "Рилс", price: 5000 },
          { name: "История", price: 3000 },
          { name: "Пост", price: 4000 },
        ],
      },
      youtube: {
        icon: "/icons/youtube.png",
        link: "https://youtube.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Интеграция", price: 15000 },
          { name: "Упоминание в видео", price: 7000 },
        ],
      },
      telegram: {
        icon: "/icons/telegram.png",
        link: "https://t.me/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 8700,
        reach: "охваты",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Реклама в посте", price: 2000 },
          { name: "Закрепленный пост", price: 5000 },
        ],
      },
      vk: {
        icon: "/icons/vk.png",
        link: "https://vk.com/blogger1",
        name: "Название канала",
        description: "описание канала описание канала описание канала описание канала описание канала",
        followers: 250,
        reach: "охваты vk",
        cpv: "cpv",
        er: "er",
        services: [
          { name: "Пост", price: 3500 },
          { name: "История", price: 2500 },
        ],
      },
    },
  },
];

export default bloggersData;
